app/models/spaceship.rb
app/views/pages/dashboard.html.erb

J'ai créé le dashboard avec 3 colonnes Spaceship / Rental / Pending Rental

dashboard init

---

app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/components/_index.scss
app/views/spaceships/new.html.erb

Change the new space ship page !

change new spaceship page

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_form.scss
app/controllers/application_controller.rb
app/controllers/spaceships_controller.rb
app/policies/application_policy.rb
app/policies/spaceship_policy.rb
app/views/spaceships/new.html.erb
test/policies/spaceship_policy_test.rb

changement de couleur page new spaceship

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/pages/_dashboard.scss
app/assets/stylesheets/pages/_index.scss
app/views/pages/dashboard.html.erb

des jolies cards avec des jolies couleurs

dashboard improved

---

app/assets/stylesheets/components/_basestylesheet.scss
app/assets/stylesheets/components/_index.scss

please check the code in basestylesheet.scss

container width changed and padded top

---

app/assets/stylesheets/pages/_dashboard.scss
app/views/pages/dashboard.html.erb

Add a spaceship button and white font

---

app/assets/stylesheets/components/_card.scss
app/views/layouts/application.html.erb
app/views/shared/_navbar.html.erb
app/views/spaceships/index.html.erb

stretched link fixed - mb navbar actualised

stretched link fixed - mb navbar actualised

---

app/assets/stylesheets/components/_form.scss
app/controllers/spaceships_controller.rb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb

changing login page and add :max_capacity, :description => spaceships controller

change login page

---

app/assets/stylesheets/components/_basestylesheet.scss
app/controllers/rentals_controller.rb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb

check the homepage html erb and application .html erb

Fix homepage container

---

app/views/spaceships/index.html.erb

Hello les beegees j'ai viré la description dans la card => spaceship index

update view spaceship index => supp card description

---

app/views/spaceships/index.html.erb

juste la photo de l'owner en plus cest les cartes spaceships

add owner picture on spaceships index

---

app/views/spaceships/show.html.erb

boutons de la show en bas avec space between

btn show flexbox at the bottom

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_card.scss

avatar upper & bigger, border corrections

---

app/assets/config/manifest.js
app/controllers/spaceships_controller.rb
app/models/spaceship.rb
app/views/spaceships/index.html.erb

Goodsearch

---

app/assets/javascripts/cable.js
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_searchbar.scss
app/views/spaceships/index.html.erb

css search bar

---

app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

final commit

---

app/assets/stylesheets/components/_navbar.scss

jabbarentals

---

Gemfile
Gemfile.lock
app/controllers/spaceships_controller.rb
app/models/spaceship.rb
app/views/spaceships/index.html.erb
config/routes.rb

Ajout de filtre search bar ; change files : => spaceship(model, controller, view index) routes + ressources :search

searchbar with filter

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/pages/_spaceship.scss
app/controllers/spaceships_controller.rb
app/views/spaceships/show.html.erb

La page des problèmes => changement de place des div et ajout du calendrier

Calendartoview

---

app/assets/stylesheets/pages/_spaceship.scss
app/controllers/reviews_controller.rb
app/controllers/spaceships_controller.rb
app/javascript/packs/application.js
app/javascript/plugins/init_star_rating.js
app/models/review.rb
app/models/spaceship.rb
app/views/reviews/create.js.erb
app/views/spaceships/show.html.erb
config/routes.rb
db/migrate/20190528095452_create_reviews.rb
db/schema.rb
package.json
test/controllers/reviews_controller_test.rb
test/models/review_test.rb
yarn.lock

review added with nice stars and some AJAX

---

app/assets/stylesheets/pages/_home.scss
app/controllers/rentals_controller.rb
app/javascript/packs/application.js
app/views/pages/home.html.erb
app/views/rentals/new.html.erb

Availability

---

app/controllers/rentals_controller.rb
app/controllers/spaceships_controller.rb
app/views/layouts/application.html.erb
app/views/spaceships/show.html.erb

Availability in show OK

---

app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/pages/_spaceship.scss
app/views/spaceships/show.html.erb

editspaceshipview

---

app/javascript/packs/application.js
app/javascript/plugins/init_star_rating.js
app/views/reviews/_count.html.erb
app/views/reviews/_form.html.erb
app/views/reviews/_show.html.erb
app/views/reviews/create.js.erb
app/views/spaceships/show.html.erb

AJAX working, reviews count, stars ok when updated

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

Done with the navbar
